# Generated by Django 6.0.1 on 2026-01-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_core', '0002_alter_post_classroom_alter_post_image_conversation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
