# Generated by Django 6.0.1 on 2026-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='Est directeur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Est parent'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Est professeur'),
        ),
    ]
